name: Python_3.9

on: workflow_dispatch

jobs:
  run-python:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: (python -c "import sys; print(sys.version)") > python_version_3.9.txt




      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: python-version-artifact-3.9
          path: python_version_3.9.txt
